# Generated by Django 3.1.6 on 2021-02-19 14:02

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
            ],
            options={
                'db_table': 'profile_users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='text')),
                ('publication_date', models.DateField(verbose_name='pub_date')),
                ('number_of_flags', models.IntegerField(default=0, verbose_name='flagged')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_id', to='minitwit.profileuser')),
            ],
            options={
                'db_table': 'messages',
            },
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_id', to='minitwit.profileuser')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whom_id', to='minitwit.profileuser')),
            ],
            options={
                'db_table': 'followers',
            },
        ),
    ]
