# Generated by Django 3.1.3 on 2021-02-12 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=70, verbose_name='user')),
                ('email', models.CharField(max_length=70, verbose_name='email')),
                ('pwd_hash', models.CharField(max_length=150, verbose_name='pwd_hash')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='text')),
                ('publication_date', models.DateField(verbose_name='pub_date')),
                ('number_of_flags', models.IntegerField(default=0, verbose_name='flagged')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_id', to='minitwit.user')),
            ],
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_id', to='minitwit.user')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whom_id', to='minitwit.user')),
            ],
        ),
    ]
