# Generated by Django 3.1.3 on 2021-02-12 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minitwit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='follower',
            table='followers',
        ),
        migrations.AlterModelTable(
            name='message',
            table='messages',
        ),
        migrations.AlterModelTable(
            name='user',
            table='twiiter_users',
        ),
    ]
