version: '3'

services:
  database:
    container_name: prod_database_minitwit
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "superuser"
      POSTGRES_PASSWORD: "su"
      POSTGRES_DB: "database_minitwit"
    ports:
      - "5555:5432"
    volumes:
      - "database-data:/var/lib/postgresql/data/"
  
  web:
    container_name: prod_web_minitwit
    image: andersstendevad/minitwit_web:prod
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      - "database"
      - "api"
    ports:
      - "8000:8000"

  api:
    container_name: prod_api_minitwit
    image: andersstendevad/minitwit_api:prod
    command: ./start.sh
    depends_on:
      - "database"
      - "prometheus"
      - "grafana"
    ports:
      - "8080:8080"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

  prometheus:
    image: prom/prometheus:v2.1.0
    volumes:
      - .:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    environment:
      - HOST_IP=http://157.230.77.141:9090


volumes:
  database-data:
