version: '3'

services:
  database:
    container_name: database_minitwit
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "superuser"
      POSTGRES_PASSWORD: "su"
      POSTGRES_DB: "database_minitwit"
    ports:
      - "5555:5432"
    volumes:
      - "database-data:/var/lib/postgresql/data/"
  web:
    container_name: web_minitwit
    build: ./Web
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      - "database"
      - "api"
    ports:
      - "8000:8000"
  api:
    container_name: api_minitwit
    build: ./Api
    command: ./start.sh
    depends_on:
      - "database"
    ports:
      - "8080:8080"
  
  api_test:
    container_name: api_minitwit_test
    build: ./Api
    command: python3 manage.py test .
    depends_on:
      - "api"
      - "database"
      
volumes:
  database-data:
