version: '3'

services:
  database:
    container_name: database_minitwit
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "superuser"
      POSTGRES_PASSWORD: "su"
      POSTGRES_DB: "database_minitwit"
    ports:
      - "5555:5432"
    volumes:
      - "database-data:/var/lib/postgresql/data/"
  web:
    container_name: web_minitwit
    build: ./Web
    depends_on:
      - "database"
    ports:
      - "8000:8000"
    volumes:
      - "./Web/itu_minitwit:/itu_minitwit"
  api:
    container_name: api_minitwit
    build: ./Api
    depends_on:
      - "database"
      - "prometheus"
      - "grafana"
    ports:
      - "8080:8080"
    volumes:
      - "./Api/minitwitAPI:/minitwitAPI"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

  prometheus:
    image: prom/prometheus:v2.1.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
volumes:
  database-data:
