apiVersion: v1
kind: Service
metadata:
  labels:
    api.service: web
  name: web
  namespace: minitwit
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 8000
  selector:
    api.service: web
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: minitwit
  labels:
    api.service: web
spec:
  replicas: 2
  selector:
    matchLabels:
      api.service: web
  template:
    metadata:
      labels:
        api.service: web
    spec:
      containers:
        - args:
            - python3
            - manage.py
            - runserver
            - 0.0.0.0:8000
          image: andersstendevad/minitwit_web:latest
          name: web
          ports:
            - containerPort: 8000
      restartPolicy: Always
