
name: Build LaTeX report

on:
  push:
    branches: [ report, main ]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          working_directory: report/
          args: -f

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'main'
          message: 'publish report.pdf'
          force: 'true'
          directory: ./report
          author_email: edibegovic@gmail.com