name: quality_assurance

on:
  push:
    branches: [ development ]

jobs:
  test_and_deploy_to_dockerhub:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: get version
        run: |
          VERSION="cat VERSION" && echo "version: $version"

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install requirements
        run: |
          python -m pip install -r requirements.txt

      - name: Test Api and Web
        timeout-minutes: 10
        run: |
          ./test_all_containers.sh

      - name: Run black on code
        run: |
          black --check .
        continue-on-error: True

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push Api
        id: docker_build_api
        uses: docker/build-push-action@v2
        with:
          context: ./Api
          push: true
          tags: andersstendevad/minitwit_api:latest
      -
        name: Build and push Web
        id: docker_build_web
        uses: docker/build-push-action@v2
        with:
          context: ./Web
          push: true
          tags: andersstendevad/minitwit_web:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
